### ISSUE TITLE
Contemplate changing default port from 9000 to another (9001)

### ISSUE THREAD

**Issue by cybtachyon** [lud2k/grunt-serve#13]
As per https://xdebug.org/docs/all_settings#remote_port , xdebug sits on 9000 as a default.

This means if you're XDebugging a PHP Rest server for your angular patternfly app, you'll need to swap one of the ports - and go figure neither give the most helpful of error messages when running into the issues.

I understand that `grunt serve` has been using 9000 since 2014, but Xdebug has been using it since 2002.

To avoid bikeshedding, **I would like to suggest we either go with 9001 or decide to ignore the issue and make it the burden of the developer to be aware of the possible port conflict**.

Note: _Many Apache Tomcat apps use 9001 and 9002, however most have FAQS that these ports tend to conflict anyways with instructions for changing them._

**Comment by srescio** [comment]
the server port can be already configured and overridden:
https://github.com/lud2k/grunt-serve#optionsport

example:
```
    grunt.initConfig({
        serve: {
            options: {
                port: serverPort
            }
        }
    });
```

**Comment by cybtachyon** [comment]
This issue is **not** about configuring or overriding the server port.

This issue is about changing the **default** port from 9000 to another (9001).

**Comment by srescio** [comment]
not everyone uses xdebug (I don't) nor it's possible to know the default port of every single debug tool (or any individual project config), having a configurable port serves that purpose

**Comment by cybtachyon** [comment]
Closing since this is extremely stale and there is not sufficient traction to merit introducing a PR.

Thanks all!
